language: python
python:
    -"2.7.9"

install:
    "pip install -r requerimientos.txt"

before_script:
    - autopep8 -ir *
    - flake8 --max--complexity=5 --exclude=*.txt,*.md *

script:
    - python TestCalculadora
